### ISSUE TITLE
出力例がない問題の場合にmix atcoder.new が途中でコケる

### ISSUE THREAD

**Issue by tamanugi** [tamanugi/ex_at_coder#4]
**Reproduce**

```
$ mix atcoder.new abc191
```

**Comment by TORIFUKUKaiou** [comment]
- 私も遭遇しましてIsuueをあげようとしていました
- 強引ですが以下のようにすると動きました

```elixir:lib/mix/tasks/atcoder/new.ex
        |> Enum.map(fn
          {n, [input: input, output: output]} -> testcase_yaml(n, input, output)
          {n, [input: input]} -> testcase_yaml(n, input, "")
        end)
```

- ここに突入する手前のRepo.task_cases/1 のほうを修正したほうがいいのかどうかはわかりませんでした
- よろしくお願いします 🙏

**Comment by tamanugi** [comment]
@TORIFUKUKaiou 

ありがとうございます！！　
https://github.com/tamanugi/ex_at_coder/pull/5
の PR で修正しました。

また修正したものを 0.2.2 にてhexにリリースいたしました ✨
